import type { Metadata, Viewport } from 'next';
import './globals.css';

/**
 * Fonts are self-hosted (app/fonts.css, generated by scripts/fetch-fonts.mjs) rather than
 * loaded through next/font/google, so a production build never depends on reaching
 * fonts.googleapis.com.
 *
 * The name uses Aref Ruqaa, not Aref Ruqaa Ink: the "Ink" cut is a COLRv1 colour font that
 * paints its own red ink from an embedded palette and ignores `color`, and recolouring it
 * needs `font-palette`, which older iOS Safari does not support.
 */
export const metadata: Metadata = {
  title: 'دعوة تخرّج كايلا',
  description: 'دعوة لمشاركة لحظة تخرّج كايلا — السبت 15 آب 2026',
  robots: { index: false, follow: false },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  themeColor: '#faf7f2',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
