import { mkdirSync, writeFileSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

/**
 * Downloads exactly the weights and subsets the invitation uses and writes them into
 * app/fonts, plus an @font-face sheet with Google's own unicode-ranges.
 *
 * Self-hosting rather than next/font/google on purpose: the production build must not
 * depend on reaching fonts.googleapis.com.
 *
 * The `latin` subset is included alongside `arabic` because the invitation prints Western
 * digits — "الساعة 7:00" and "15 آب 2026" — which live in the latin range, not the arabic one.
 */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Aref Ruqaa', css: 'Aref+Ruqaa', weights: [700], slug: 'aref-ruqaa' },
  { name: 'Noto Naskh Arabic', css: 'Noto+Naskh+Arabic', weights: [500, 600], slug: 'noto-naskh-arabic' },
  { name: 'IBM Plex Sans Arabic', css: 'IBM+Plex+Sans+Arabic', weights: [500, 600], slug: 'ibm-plex-sans-arabic' },
];

const KEEP_SUBSETS = new Set(['arabic', 'latin']);

/**
 * Downloads go through curl, not node's fetch. Several of Google's A records are
 * unreachable from this network and undici stalls on them; curl negotiates a working
 * address. `--retry` covers the flaky ones.
 */
const curlText = (url) =>
  execFileSync('curl', ['-sS', '--fail', '--retry', '4', '--retry-all-errors', '--max-time', '45', '-A', UA, url], {
    encoding: 'utf8',
    maxBuffer: 1024 * 1024 * 32,
  });

const curlFile = (url, dest) =>
  execFileSync('curl', ['-sS', '--fail', '--retry', '4', '--retry-all-errors', '--max-time', '60', '-A', UA, '-o', dest, url]);

mkdirSync('app/fonts', { recursive: true });

const faces = [];

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.css}:wght@${family.weights.join(';')}&display=swap`;
  const css = curlText(url);

  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g)];
  if (!blocks.length) throw new Error(`no @font-face blocks parsed for ${family.name}`);

  for (const [, subset, body] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) continue;

    const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
    const src = body.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (!weight || !src || !range) continue;

    const file = `${family.slug}-${weight}-${subset}.woff2`;
    curlFile(src, `app/fonts/${file}`);
    const kb = statSync(`app/fonts/${file}`).size / 1024;

    faces.push({ family: family.name, weight, subset, file, range, kb });
    console.log(`  ${file.padEnd(42)} ${kb.toFixed(1)}kB`);
  }
}

const sheet = `/*
 * Generated by scripts/fetch-fonts.mjs — do not edit by hand.
 * Self-hosted so the production build never needs to reach Google Fonts.
 */
${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
  )
  .join('\n\n')}
`;

writeFileSync('app/fonts.css', sheet);
console.log(`\n${faces.length} font files, ${faces.reduce((a, f) => a + f.kb, 0).toFixed(0)}kB total → app/fonts.css`);
